### ISSUE TITLE
[BUG] Not compatible with Illustrator 28.6

### ISSUE THREAD

**Issue by emanuelbg** [mevCJ/logo-packer#16]
**OS:**
 - OS: Windows 11

**Describe the bug**
It's not compatible with new version of Illustrator 28.6

**Screenshots**
![image](https://github.com/user-attachments/assets/bd67c541-6ce4-455b-a3f6-0d883c1785d4)

**Additional context**

**Comment by schroef** [comment]
Tha is, indeed it needs to be updated. @mevCJ is the one which can update in adobe cloud. This does take a little since adobe needs to verify it.

You could adjust a file in one of the folders, but I believe the plugin needs to be able to run in developper mode

You can try to edit this file in the folder CSXS and than the line where you see 28.5, change that to 28.6

If it still doesn't show, than we need to set the system to debug mode. That's a bit more work, so let me know if your willing to do so. Otherwise we need to wait untill @mevCJ  updates it and it's is approved bu Adobe

![Screenshot_20240730_112959_GitHub.png](https://github.com/user-attachments/assets/a4b5a0d0-a93f-4449-a738-bee44d442248)

Ps om the readme page of the repo, you can find out how to adjust it for manual install. Since you already have it, we can adjust only the file.
Do you happen to know which version of the extension you are running? You can see that in the fly out panel, small hamburger menu

**Comment by emanuelbg** [comment]
Thanks, it works here. I uninstalled it from Adobe Exchange and needed to install it manually. After that, I adjusted the code to 28.6 and the extension works again.

**Comment by mevCJ** [comment]
Hi @emanuelbg The latest version has been submitted for review on Adobe Exchange. Thanks for raising up the issue.

@schroef  Thanks for the prompt reply!

**Comment by schroef** [comment]
> Thanks, it works here. I uninstalled it from Adobe Exchange and needed to install it manually. After that, I adjusted the code to 28.6 and the extension works again.

Just curious, you have to do the commands in the command tool, correct?

**Comment by emanuelbg** [comment]
> > Thanks, it works here. I uninstalled it from Adobe Exchange and needed to install it manually. After that, I adjusted the code to 28.6 and the extension works again.
> 
> Just curious, you have to do the commands in the command tool, correct?

No, I just changed the .xml file and saved it

**Comment by schroef** [comment]
Okay, that's strange. But glad it works now
