### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by vehaarevnah** [mevCJ/logo-packer#8]
Hi @schroef, 

I am using your awesome app, thank you - it definitely saves a lot of time - but had three questions:

1) Is there an option to export as EPS? How can this be added?
2) Is there an option to export the Inverse version of a logo? (Meaning, the accent color and white together so that it can show up on a dark background, as opposed to a fully white version) How can this be added?
3) Also is there an option for RGB?

Looking forward to hearing how we can resolve the three of these, thanks!

**Comment by schroef** [comment]
I'm rethinking this and probably will. Personally I hardly ever use the format, its old and not sued a lot.

I'm thinking about adding better export settings. Like having its own complete panel. I guess I will add a tabbed design so that users can add specifics settings per file format

For the inverse color method i would need to rethink that. The down side to this is, it will only work when the logomark is made of a single color. Because that will be used to check what needs to be kept. Or when a saved gradient is used, I'll think that will work as well.

Concerning the RGB export, that is available, you need to use the Display mode then. It's when you generate the logos, you need to pick everything ther print (cmtk) or digital (rgb)

Hope this helps

**Comment by schroef** [comment]
1. the latest released now has EPS again
2. The extension is not sophisticated enough todo that. However, after the logo versions have been created, you can manually tweak the logo before you do the export.
3. RGB mode is already there

**Comment by thirdeyeapparelcompany** [comment]
i got the plugin but it looks nothing like the instuctions on how to use it. it wont allow me to drop my logo into the field that says drop items here or whatever

**Comment by schroef** [comment]
@thirdeyeapparelcompany 

What does the error state?

Probably you forgot either, clientname, logotype, display or print or set dash or underscore. These need to be set first before you are able to do than. It shows what is not set in the short error it displays

**Comment by thirdeyeapparelcompany** [comment]
I did get it to work. I think I was forgetting client name. Does it do
anything besides invert and make an all white logo? I can tell you an easy
way to make a logo variation that's only a couple steps if you program it.
Simply add a black offset path of 5pt. The original black simple logo then
switch to white creating a professional looking design out of a simple one.
Thanks for your help

**Comment by schroef** [comment]
> I did get it to work. I think I was forgetting client name. Does it do anything besides invert and make an all white logo? I can tell you an easy way to make a logo variation that's only a couple steps if you program it. Simply add a blac

@thirdeyeapparelcompany 
Could you show an example image perhaps?

**Comment by schroef** [comment]
@vehaarevnah 
@thirdeyeapparelcompany 

Im working on a branch which also can do inverted logo. Ive been doing 100s of tests, tried many different logo's i have and it seems to work properly. Ill make a branch for it this week and share a link

Ive made another branch, its here; https://github.com/mevCJ/logo-packer/pull/12
I added a short description how it works with the inverted logo type. I hope users understand the workflow

**Comment by schroef** [comment]
@vehaarevnah 

all you question are added and now are available in the main branch
